### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 55tommy** [55tommy/protospace-38555#1]
#URL
 https://protospace-38555.herokuapp.com/

**Comment by shodai-ito** [comment]
@55tommy さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`コメント機能`**
- [x] フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること
自身のプロトタイプに空のフォームでコメントすると、留まらずにエラーになってしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by 55tommy** [comment]
レビューありがとうございます。
修正いたしましたので、ご確認よろしくお願いいたします。

#URL
https://protospace-38555.herokuapp.com/

**Comment by snkw-works** [comment]
@55tommy さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by 55tommy** [comment]
添削ありがとうございました。
